In [431]:
using Revise
using LinearAlgebra
using Statistics
using BenchmarkTools
using OrthoMatchPursuit
using BlockDiagonal

In [234]:
# b = randn(5)
# @show norm(b)
# v = deepcopy(b)
# bcopy = deepcopy(b)

# τ = deepcopy(LinearAlgebra.reflector!(v))

# Hb = LinearAlgebra.reflectorApply!(v, τ, repeat(b, 1, 1))

# @show Hb
# @show norm(bcopy)
# @show -norm(bcopy)*sign(bcopy[1]);

norm(b) = 1.9387212353251706
Hb = [-1.9387212353251708; 2.220446049250313e-16; -2.220446049250313e-16; -1.1102230246251565e-16; 1.1102230246251565e-16]
norm(bcopy) = 1.9387212353251706
-(norm(bcopy)) * sign(bcopy[1]) = -1.9387212353251706


In [432]:
A = randn(10,3)
a = randn(10)
x = randn(10)

┌ Error: Failed to revise /media/mat/HDD/QROMP/src/QROMP.jl
│   exception = (LoadError("/media/mat/HDD/QROMP/src/omp.jl", 2, "extra token \"qromp\" after end of expression"), Union{Ptr{Nothing}, Base.InterpreterIP}[Ptr{Nothing} @0x00007f3f06d09d6f])
└ @ Revise /home/mat/.julia/packages/Revise/VxkZO/src/packagedef.jl:709
┌ Warning: The running code does not match the saved version for the following files:
│ 
│   /media/mat/HDD/QROMP/src/QROMP.jl
│ 
│ If the error was due to evaluation order, it can sometimes be resolved by calling `Revise.retry()`.
│ Use Revise.errors() to report errors again. Only the first error in each file is shown.
│ Your prompt color may be yellow until the errors are resolved.
└ @ Revise /home/mat/.julia/packages/Revise/VxkZO/src/packagedef.jl:805


10-element Array{Float64,1}:
  0.5986771487001168
 -0.5156746056068436
 -1.1611010088921945
 -0.3012604575660464
  0.7900111214585174
  0.4528742221821375
  0.7672310779923338
  0.43162597595934865
  0.08571135210296504
  1.408885724403851

In [433]:
Revise.errors()

┌ Error: Failed to revise /media/mat/HDD/QROMP/src/QROMP.jl
│   exception = (LoadError("/media/mat/HDD/QROMP/src/omp.jl", 2, "extra token \"qromp\" after end of expression"), Union{Ptr{Nothing}, Base.InterpreterIP}[Ptr{Nothing} @0x00007f3f06d09d6f])
└ @ Revise /home/mat/.julia/packages/Revise/VxkZO/src/packagedef.jl:709


In [444]:
e3 = zeros(3)
e3[3] = 1.0;

In [ ]:
F.Q

In [445]:
@time F.Q*e3

  0.000018 seconds (6 allocations: 33.266 KiB)


10-element Array{Float64,1}:
  0.06191472674149346
 -0.1640317263698367
 -0.11725278744850189
  0.046235669654531616
 -0.26444855813209905
 -0.5344310477549761
  0.1748911301891737
 -0.41511678634223265
  0.1529498323492136
  0.609526140869759

In [435]:
mul!()

QR{Float64,Array{Float64,2}}
Q factor:
10×10 LinearAlgebra.QRPackedQ{Float64,Array{Float64,2}}:
 -0.457073  -0.103649    0.0619147  …  -0.259563    0.174161    -0.0796082
  0.207095  -0.352342   -0.164032       0.459939   -0.505941     0.414787
  0.111411  -0.0495328  -0.117253      -0.445225    0.188201     0.584809
  0.183859   0.0903155   0.0462357      0.0286187  -0.00386806  -0.035748
  0.610597   0.51292    -0.264449      -0.163912    0.150773     0.0430183
 -0.201844  -0.220646   -0.534431   …  -0.198959    0.0556882    0.313766
  0.235763   0.0285814   0.174891       0.118486   -0.060827    -0.0838439
 -0.34952    0.44087    -0.415117       0.58281     0.302516     0.0887034
  0.280689  -0.480824    0.15295        0.301781    0.745723     0.0505079
 -0.178538   0.34111     0.609526       0.103961    0.033247     0.600488
R factor:
3×3 Array{Float64,2}:
 -2.89513   0.809285   0.240199
  0.0      -2.90613   -0.78468
  0.0       0.0       -2.41183

In [408]:
v1 = deepcopy(A[:,1])
v1[1] += sign(A[1,1])*norm(A[:,1])
v1 ./= norm(v1)

10-element Array{Float64,1}:
  0.8535433542386791
 -0.12131465381844189
 -0.06526407278195857
 -0.10770312613985521
 -0.35768382364888446
  0.11823890871974659
 -0.1381081086386934
  0.20474633406399048
 -0.16442550436291942
  0.10458642322398448

In [409]:
A[:,1]-2*v1*(v1'*A[:,1])

10-element Array{Float64,1}:
 -2.8951281017980177
 -1.1102230246251565e-16
 -5.551115123125783e-17
 -1.1102230246251565e-16
 -4.440892098500626e-16
  1.1102230246251565e-16
 -1.1102230246251565e-16
  2.220446049250313e-16
 -2.220446049250313e-16
  1.1102230246251565e-16

In [410]:
-sign(A[1,1])*norm(A[:,1])

-2.8951281017980186

In [411]:
F = qrfactUnblocked(A);

In [415]:
@time (Matrix(F.Q)[:,end]'*a)*Matrix(F.Q)[:,end]

  0.000034 seconds (19 allocations: 68.781 KiB)


10-element Array{Float64,1}:
 -0.06386513025644856
  0.16919896318914218
  0.1209464199784922
 -0.047692160175551175
  0.27277907050695205
  0.5512663993570996
 -0.18040045394795617
  0.42819356600047437
 -0.1577679734656433
 -0.628727096606396

In [430]:
@time q = F.Q*e3
@time (q'*a)*q

  0.000016 seconds (5 allocations: 33.125 KiB)
  0.000139 seconds (491 allocations: 3.894 MiB)
  0.000008 seconds (5 allocations: 400 bytes)


10-element SparseVector{Float64,Int64} with 10 stored entries:
  [1 ]  =  -0.0638651
  [2 ]  =  0.169199
  [3 ]  =  0.120946
  [4 ]  =  -0.0476922
  [5 ]  =  0.272779
  [6 ]  =  0.551266
  [7 ]  =  -0.1804
  [8 ]  =  0.428194
  [9 ]  =  -0.157768
  [10]  =  -0.628727

In [429]:
e3s = sparse(e3)

10-element SparseVector{Float64,Int64} with 1 stored entry:
  [3 ]  =  1.0

In [383]:
G = qrfactUnblocked(hcat(A, a));

In [384]:
e3 = zeros(10)
e3[end] = 1.0;

In [385]:
F.factors

200×3 Array{Float64,2}:
 -14.1094       -0.0654877    1.99214
  -0.0588622   -14.1452      -0.466042
  -0.0183108     0.0284008   13.9111
  -0.0100534    -0.00194177   0.018311
   0.0188217    -0.0393184   -0.0234043
  -0.0129462    -0.0785732   -0.00634784
   0.0160007    -0.0284011    0.048103
   0.0488026     0.00776005   0.00817411
   0.0941817    -0.0433128   -0.0100144
  -0.00429275   -0.0117351   -0.0229985
   0.0541583     0.0234308   -0.0527693
  -0.0225049    -0.0896983   -0.105128
  -0.117634     -0.024595    -0.0134091
   ⋮                         
   0.00131247   -0.0376595   -0.0698185
   0.168875     -0.0129279    0.0407923
   0.044295     -0.140042     0.00320451
   0.0163201     0.0653219   -0.0262784
   0.0273254     0.0352246   -0.0251268
   0.0948909    -0.0285522   -0.0593608
   0.00146409   -0.0890485   -0.0515669
   0.0886513    -0.0671356   -0.0521009
  -0.0460098     0.0197032    7.51462e-5
   0.0956575     0.0214919   -0.0564397
   0.0580051    -0.113593    -0

In [386]:
F.τ

3-element Array{Float64,1}:
 1.067959993142783
 1.0067138556018416
 1.092812610421512

In [387]:
F.Q*e3

LoadError: DimensionMismatch("vector must have length either 200 or 3")

In [388]:
Matrix(F.Q)

200×3 Array{Float64,2}:
 -0.06796     -0.00804195  -0.00849211
  0.0628624   -0.00624049   0.000163739
  0.0195552   -0.0284442   -0.0926667
  0.0107366    0.00203565  -0.0199245
 -0.0201008    0.039431     0.0254299
  0.0138261    0.0792048    0.00707335
 -0.0170881    0.0284631   -0.0526939
 -0.0521192   -0.00820462  -0.00934982
 -0.100582     0.0428462    0.0101586
  0.00458448   0.0118484    0.0251734
 -0.0578389   -0.0240236    0.0571991
  0.0240343    0.0904816    0.115106
  0.125628     0.0257061    0.0156609
  ⋮                        
 -0.00140167   0.0379018    0.0763
 -0.180352     0.0116566   -0.0460081
 -0.0473053    0.140626    -0.00383102
 -0.0174293   -0.0658917    0.0285569
 -0.0291824   -0.0356808    0.0272149
 -0.10134      0.0279807    0.064074
 -0.00156359   0.0896346    0.0563704
 -0.0946761    0.0668734    0.0562062
  0.0491367   -0.0194654    0.000301977
 -0.102158    -0.0224055    0.0608585
 -0.0619472    0.113889     0.0539674
  0.0688736   -0.0907754    0.055

In [448]:
?ldiv!

search: ldiv! splitdrive



```
ldiv!(Y, A, B) -> Y
```

Compute `A \ B` in-place and store the result in `Y`, returning the result.

The argument `A` should *not* be a matrix.  Rather, instead of matrices it should be a factorization object (e.g. produced by [`factorize`](@ref) or [`cholesky`](@ref)). The reason for this is that factorization itself is both expensive and typically allocates memory (although it can also be done in-place via, e.g., [`lu!`](@ref)), and performance-critical situations requiring `ldiv!` usually also require fine-grained control over the factorization of `A`.

# Examples

```jldoctest
julia> A = [1 2.2 4; 3.1 0.2 3; 4 1 2];

julia> X = [1; 2.5; 3];

julia> Y = zero(X);

julia> ldiv!(Y, qr(A), X);

julia> Y
3-element Array{Float64,1}:
  0.7128099173553719
 -0.051652892561983674
  0.10020661157024757

julia> A\X
3-element Array{Float64,1}:
  0.7128099173553719
 -0.05165289256198333
  0.10020661157024785
```

---

```
ldiv!(A, B)
```

Compute `A \ B` in-place and overwriting `B` to store the result.

The argument `A` should *not* be a matrix.  Rather, instead of matrices it should be a factorization object (e.g. produced by [`factorize`](@ref) or [`cholesky`](@ref)). The reason for this is that factorization itself is both expensive and typically allocates memory (although it can also be done in-place via, e.g., [`lu!`](@ref)), and performance-critical situations requiring `ldiv!` usually also require fine-grained control over the factorization of `A`.

# Examples

```jldoctest
julia> A = [1 2.2 4; 3.1 0.2 3; 4 1 2];

julia> X = [1; 2.5; 3];

julia> Y = copy(X);

julia> ldiv!(qr(A), X);

julia> X
3-element Array{Float64,1}:
  0.7128099173553719
 -0.051652892561983674
  0.10020661157024757

julia> A\Y
3-element Array{Float64,1}:
  0.7128099173553719
 -0.05165289256198333
  0.10020661157024785
```

---

```
ldiv!(a::Number, B::AbstractArray)
```

Divide each entry in an array `B` by a scalar `a` overwriting `B` in-place.  Use [`rdiv!`](@ref) to divide scalar from right.

# Examples

```jldoctest
julia> B = [1.0 2.0; 3.0 4.0]
2×2 Array{Float64,2}:
 1.0  2.0
 3.0  4.0

julia> ldiv!(2.0, B)
2×2 Array{Float64,2}:
 0.5  1.0
 1.5  2.0
```


In [395]:
@time F = updateqrfactUnblocked!(F, a)

  0.000023 seconds (7 allocations: 42.703 KiB)


QR{Float64,Array{Float64,2}}
Q factor:
200×200 LinearAlgebra.QRPackedQ{Float64,Array{Float64,2}}:
 -0.06796     -0.00804195  -0.00849211   …  -0.0481424     0.0672316
  0.0628624   -0.00624049   0.000163739      0.117278     -0.0962472
  0.0195552   -0.0284442   -0.0926667        0.0580183     0.0503943
  0.0107366    0.00203565  -0.0199245       -0.0180354     0.00487727
 -0.0201008    0.039431     0.0254299        0.093043      0.0555233
  0.0138261    0.0792048    0.00707335   …  -0.0100423     0.00511721
 -0.0170881    0.0284631   -0.0526939        0.000913912   0.00796371
 -0.0521192   -0.00820462  -0.00934982      -0.00465951    0.000669842
 -0.100582     0.0428462    0.0101586       -0.00979569    0.00993843
  0.00458448   0.0118484    0.0251734        0.00139562    0.00216605
 -0.0578389   -0.0240236    0.0571991    …   0.00181719    0.00164766
  0.0240343    0.0904816    0.115106        -0.0132523     0.00218484
  0.125628     0.0257061    0.0156609       -0.00358715   -0.0102

In [396]:
@btime begin
    A = randn(500,1)
    ϕ = randn(500)
    for i=1:99
    A = hcat(A, ϕ)
    end
end

  1.135 ms (197 allocations: 19.28 MiB)


In [398]:
@btime begin
    A = randn(500,20)
    G = qrfactUnblocked(view(A,:,1:1))
    for i=2:20
    G = updateqrfactUnblocked!(G, view(A,:,i))
    end
end

  203.395 μs (138 allocations: 1.57 MiB)


In [400]:
@btime begin
    A = randn(500,20)
    for i=1:20
    G = qrfactUnblocked(view(A,:,1:i))
    end
end

  920.145 μs (58 allocations: 903.86 KiB)


In [394]:
@time qrfactUnblocked(hcat(A, a))

  0.000019 seconds (4 allocations: 12.891 KiB)


QR{Float64,Array{Float64,2}}
Q factor:
200×200 LinearAlgebra.QRPackedQ{Float64,Array{Float64,2}}:
 -0.06796     -0.00804195  -0.00849211   …  -0.0450985    0.0687535
  0.0628624   -0.00624049   0.000163739      0.113702    -0.0980353
  0.0195552   -0.0284442   -0.0926667        0.0540416    0.0484059
  0.0107366    0.00203565  -0.0199245        0.0856018    0.0566959
 -0.0201008    0.039431     0.0254299        0.00592122   0.0119624
  0.0138261    0.0792048    0.00707335   …  -0.00998851   0.0051441
 -0.0170881    0.0284631   -0.0526939        0.00146049   0.008237
 -0.0521192   -0.00820462  -0.00934982      -0.00405655   0.000971325
 -0.100582     0.0428462    0.0101586       -0.00934857   0.010162
  0.00458448   0.0118484    0.0251734        0.00215686   0.00254667
 -0.0578389   -0.0240236    0.0571991    …   0.0019634    0.00172076
  0.0240343    0.0904816    0.115106        -0.0122508    0.00268563
  0.125628     0.0257061    0.0156609       -0.00437045  -0.010656
  ⋮             

In [262]:
F = qrfactUnblocked(A)

QR{Float64,Array{Float64,2}}
Q factor:
5×5 LinearAlgebra.QRPackedQ{Float64,Array{Float64,2}}:
 -0.354453  -0.0294567  -0.144777   0.780108   -0.49393
  0.608479  -0.0560666  -0.699902  -0.0836116  -0.360217
  0.360319   0.842926    0.108657   0.335093    0.188553
  0.596943  -0.50698     0.442864   0.416633    0.130075
 -0.133963  -0.168629   -0.530323   0.313959    0.757499
R factor:
3×3 Array{Float64,2}:
 -1.70342   0.381944  -0.401239
  0.0      -2.49682    0.0895945
  0.0       0.0        1.17001

In [263]:
G = qrfactUnblocked(hcat(A, a))

QR{Float64,Array{Float64,2}}
Q factor:
5×5 LinearAlgebra.QRPackedQ{Float64,Array{Float64,2}}:
 -0.354453  -0.0294567  -0.144777   0.0496505  -0.921992
  0.608479  -0.0560666  -0.699902   0.355129   -0.103107
  0.360319   0.842926    0.108657  -0.328272   -0.200192
  0.596943  -0.50698     0.442864  -0.317106   -0.29991
 -0.133963  -0.168629   -0.530323  -0.814309    0.0963116
R factor:
4×4 Array{Float64,2}:
 -1.70342   0.381944  -0.401239    0.39236
  0.0      -2.49682    0.0895945  -0.297712
  0.0       0.0        1.17001     1.68256
  0.0       0.0        0.0         1.92161

In [273]:
F.Q*I

5×5 Array{Float64,2}:
 -0.354453  -0.0294567  -0.144777   0.780108   -0.49393
  0.608479  -0.0560666  -0.699902  -0.0836116  -0.360217
  0.360319   0.842926    0.108657   0.335093    0.188553
  0.596943  -0.50698     0.442864   0.416633    0.130075
 -0.133963  -0.168629   -0.530323   0.313959    0.757499

In [274]:
G.Q*I

5×5 Array{Float64,2}:
 -0.354453  -0.0294567  -0.144777   0.0496505  -0.921992
  0.608479  -0.0560666  -0.699902   0.355129   -0.103107
  0.360319   0.842926    0.108657  -0.328272   -0.200192
  0.596943  -0.50698     0.442864  -0.317106   -0.29991
 -0.133963  -0.168629   -0.530323  -0.814309    0.0963116

In [267]:
Matrix(G.Q)

5×4 Array{Float64,2}:
 -0.354453  -0.0294567  -0.144777   0.0496505
  0.608479  -0.0560666  -0.699902   0.355129
  0.360319   0.842926    0.108657  -0.328272
  0.596943  -0.50698     0.442864  -0.317106
 -0.133963  -0.168629   -0.530323  -0.814309

In [268]:
@time Matrix(G.Q)[:,end]'*x

  0.000029 seconds (10 allocations: 34.359 KiB)


0.6202879075119723

In [269]:
LinearAlgebra.reflectorApply!(G.factors[:,end], G.τ[end], repeat(x, 1, 1))

5×1 Array{Float64,2}:
 4.944806387469483
 0.4039049800822969
 5.1013680207778975
 6.0383490848674235
 2.949129244600986

In [272]:
G.factors[:,end]

5-element Array{Float64,1}:
  0.3923598764754786
 -0.2977117858429559
  1.682555529563471
  1.921611896033874
  0.586019851426991

In [177]:
Matrix(F.Q)

5×3 Array{Float64,2}:
 -0.560746   0.476858  -0.595692
  0.266732  -0.163457  -0.399935
  0.152475  -0.56073   -0.65764
 -0.70258   -0.305936   0.0862987
  0.312332   0.581268  -0.212757

In [185]:
@time F.Q*e1

  0.000023 seconds (5 allocations: 33.094 KiB)


5-element Array{Float64,1}:
 -0.5607457503101241
  0.2667317833640683
  0.15247531590364338
 -0.7025797512047869
  0.3123320836700315

In [173]:
F.τ

3-element Array{Float64,1}:
 1.560745750310124
 1.0819620790792472
 1.4774117472219135

In [174]:
F.factors

5×3 Array{Float64,2}:
  1.96898     0.526254   0.0488306
 -0.1709      1.18777    0.0285602
 -0.0976939   0.475196   2.18735
  0.450156    0.48116   -0.40332
 -0.200117   -0.625434   0.437095

In [175]:
F.R

3×3 Array{Float64,2}:
 1.96898  0.526254  0.0488306
 0.0      1.18777   0.0285602
 0.0      0.0       2.18735

In [187]:
norm(bcopy)

1.0671788067058015

In [21]:
F = qrfactUnblocked(A)

QR{Float64,Array{Float64,2}}
Q factor:
5×5 LinearAlgebra.QRPackedQ{Float64,Array{Float64,2}}:
 -0.590628   0.129591   0.137759   0.597569   0.508231
  0.325049  -0.37588    0.853367   0.110796   0.112009
 -0.694451  -0.550947   0.104992  -0.329692  -0.307368
  0.201446  -0.549423  -0.364693   0.658603  -0.301323
  0.150532  -0.486325  -0.329792  -0.296952   0.737486
R factor:
3×3 Array{Float64,2}:
 -2.34065  -0.225599  -0.789926
  0.0       0.257028  -0.144538
  0.0       0.0       -2.66019

In [22]:
Matrix(F.Q)

5×3 Array{Float64,2}:
 -0.590628   0.129591   0.137759
  0.325049  -0.37588    0.853367
 -0.694451  -0.550947   0.104992
  0.201446  -0.549423  -0.364693
  0.150532  -0.486325  -0.329792

In [23]:
@time F.Q[:,4]

  0.031427 seconds (47.06 k allocations: 2.580 MiB, 25.41% gc time)


5-element Array{Float64,1}:
  0.5975693865108171
  0.11079646119980852
 -0.32969191285354693
  0.6586027905643893
 -0.2969521499340479

In [24]:
@time F.Q

  0.000003 seconds (2 allocations: 64 bytes)


5×5 LinearAlgebra.QRPackedQ{Float64,Array{Float64,2}}:
 -0.590628   0.129591   0.137759   0.597569   0.508231
  0.325049  -0.37588    0.853367   0.110796   0.112009
 -0.694451  -0.550947   0.104992  -0.329692  -0.307368
  0.201446  -0.549423  -0.364693   0.658603  -0.301323
  0.150532  -0.486325  -0.329792  -0.296952   0.737486

In [25]:
@time Matrix(F.Q)

  0.000027 seconds (6 allocations: 33.875 KiB)


5×3 Array{Float64,2}:
 -0.590628   0.129591   0.137759
  0.325049  -0.37588    0.853367
 -0.694451  -0.550947   0.104992
  0.201446  -0.549423  -0.364693
  0.150532  -0.486325  -0.329792

In [26]:
F.factors

5×3 Array{Float64,2}:
 -2.34065    -0.225599  -0.789926
 -0.204352    0.257028  -0.144538
  0.436589    0.450219  -2.66019
 -0.126645    0.394999   0.514372
 -0.0946365   0.351313   0.463336

In [27]:
fieldnames(typeof(F))

(:factors, :τ)

In [19]:
F.T

3×3 Array{Float64,2}:
 1.59063       0.195457      -0.920208
 0.0           1.3494        -1.48904
 6.91241e-310  6.91241e-310   1.35203

In [28]:
F.τ

3-element Array{Float64,1}:
 1.590627772674415
 1.3493980685712008
 1.35202857421537

In [ ]:
(I - F.factors)